### ISSUE TITLE
When number and length of pattern fields exceed certain number, the mesh with multiple pins does not work

### ISSUE THREAD

**Issue by andriy-zhelvachenko** [rjrodger/seneca-mesh#8] opened 2016-02-04 10:34 UTC
Here is the example

Server

#!/opt/local/bin/node

require('seneca')()
  //.use('mesh', {auto:true, listen:[ {pins:['ns:mmmmm,app:coi,cmd:fetch,ds:ba,w:a123456', 'ns:mmmmm,app:coi,cmd:publish,ds:ba,w:a123456'], model:'publish'}]})
  .use('mesh', {auto:true, listen:[ {pins:['ns:mmmmm,app:coi,cmd:fetch,ds:ba,w:a12345', 'ns:mmmmm,app:coi,cmd:publish,ds:ba,w:a12345'], model:'publish'}]})
  .ready(function(){
    var s = this;
    //s.add('ns:mmmmm,app:coi,cmd:fetch,ds:ba,w:a123456', function(msg, done){
    s.add('ns:mmmmm,app:coi,cmd:fetch,ds:ba,w:a12345', function(msg, done){
      console.log('Server|Fetch|Message: ' + JSON.stringify(msg));
      done(null, {status:'ok', one:'fetch'});
    });
    //s.add('ns:mmmmm,app:coi,cmd:publish,ds:ba,w:a123456', function(msg, done){
    s.add('ns:mmmmm,app:coi,cmd:publish,ds:ba,w:a12345', function(msg, done){
      console.log('Server|Publish|Message: ' + JSON.stringify(msg));
      done(null, {status:'ok', another:'publish'});
    });
  })
  .listen({port:6666})

**Comment by andriy-zhelvachenko** [comment] 2016-02-04 10:34
Here is the client

#!/opt/local/bin/node

require('seneca')()
  .use('mesh', {auto:true})
  .ready(function(){
    var s = this;
      //s.act('ns:mmmmm,app:coi,cmd:fetch,ds:ba,w:a123456', function(error, resp){
      s.act('ns:mmmmm,app:coi,cmd:fetch,ds:ba,w:a12345', function(error, resp){
        console.log('Client|Error: ' + JSON.stringify(error));
        console.log('Client|Data: ' + JSON.stringify(resp));
      }); 
      //s.act('ns:mmmmm,app:coi,cmd:publish,ds:ba,w:a123456', function(error, resp){
      s.act('ns:mmmmm,app:coi,cmd:publish,ds:ba,w:a12345', function(error, resp){
        console.log('Client|Publish|Error: ' + JSON.stringify(error));
        console.log('Client|Publish|Data: ' + JSON.stringify(resp));
      });
  });

**Comment by andriy-zhelvachenko** [comment] 2016-02-04 10:35
if you add 1 digit to each pattern, then messages matching will stop working.

I.e. feel free just to uncomment commented lines

**Comment by mcdonnelldean** [comment] 2016-02-04 10:40
@andriy-zhelvachenko Can you try with a json message instead of a jsonic string? I just want to see if the issue is actually in jsonic and not mesh.

**Comment by andriy-zhelvachenko** [comment] 2016-02-04 10:41
Right now i cannot. Have to go!

Were you able to reproduce it?

**Comment by andriy-zhelvachenko** [comment] 2016-02-04 10:44
If you meant the client, then this fails too

#!/opt/local/bin/node

require('seneca')()
  .use('mesh', {auto:true})
  .ready(function(){
    var s = this;
      s.act({ns:'mmmmm',app:'coi',cmd:'fetch',ds:'ba',w:'a123456'}, function(error, resp){
      //s.act('ns:mmmmm,app:coi,cmd:fetch,ds:ba,w:a12345', function(error, resp){
        console.log('Client|Error: ' + JSON.stringify(error));
        console.log('Client|Data: ' + JSON.stringify(resp));
      }); 
      s.act({ns:'mmmmm',app:'coi',cmd:'publish',ds:'ba',w:'a123456'}, function(error, resp){
      //s.act('ns:mmmmm,app:coi,cmd:publish,ds:ba,w:a12345', function(error, resp){
        console.log('Client|Publish|Error: ' + JSON.stringify(error));
        console.log('Client|Publish|Data: ' + JSON.stringify(resp));
      });
  });

**Comment by andriy-zhelvachenko** [comment] 2016-02-04 10:47
I have also noticed that sometimes (when i run srv.js and when it fails)

This messages is cutoff for some reason, i.e. last few characters are missing
 
INFO listen  {pins:[ns:mmmmm,app:coi,cmd:fetch,ds:ba,w:a123456,ns:mmmmm,app:coi,cmd:publish,ds:ba,w:a123456],model:publish}

**Comment by andriy-zhelvachenko** [comment] 2016-02-04 10:47
e.g. 

INFO listen  {pins:[ns:mmmmm,app:coi,cmd:fetch,ds:ba,w:a123456,ns:mmmmm,app:coi,cmd:publish,ds:ba,w:a123456],model:publi

**Comment by andriy-zhelvachenko** [comment] 2016-02-10 19:01
@rjrodger, this seems definitly to be the problem. I have hit it again.

Here is the example
https://gist.github.com/andriy-zhelvachenko/6b5d2e211a1ab900c8b7 

I have also noticed that when you start server (s2.js) with short pattern
- seneca outputs 3 ACT messages

2016-02-10T18:59:53.407Z uapzop6yakiv/1455130793383/27835/- INFO        hello   Seneca/1.1.0/uapzop6yakiv/1455130793383/27835/- 
2016-02-10T18:59:54.069Z uapzop6yakiv/1455130793383/27835/- INFO        listen  {pins:[ns:mmmmm,cmd:fetch,ns:mmmmm,cmd:publish],model:publish}  
2016-02-10T18:59:54.118Z m4erkhq3cpk8/1455129811011/27797/- INFO        -       -       ACT     holve755ask2/iyylvpnrc72x       name:mesh,plugin:define,role:seneca,seq:5,tag:undefined       plugin  mesh            ACT     hz1n7l701o75/zet7zm3u80c1       add:client,role:transport,type:balance  client  {model:publish,port:57513,type:web,host:0.0.0.0,path:null,role:transport,hook:listen} 
2016-02-10T18:59:54.121Z m4erkhq3cpk8/1455129811011/27797/- INFO        -       -       ACT     holve755ask2/iyylvpnrc72x       name:mesh,plugin:define,role:seneca,seq:5,tag:undefined       plugin  mesh            ACT     tkctpt15pkqa/zet7zm3u80c1       add:client,role:transport,type:balance  client  {model:publish,port:57513,type:web,host:0.0.0.0,path:null,role:transport,hook:listen} 
2016-02-10T18:59:54.314Z uapzop6yakiv/1455130793383/27835/- INFO        client  {type:balance,pin:role:mesh,base:true,model:actor}
2016-02-10T18:59:54.319Z uapzop6yakiv/1455130793383/27835/- INFO        -       -       ACT     k7cvgl067px4/q60c36lzn4fo       name:mesh,plugin:define,role:seneca,seq:5,tag:undefined       plugin  mesh            ACT     6idcv3wfz0jr/pywn9i681uk4       add:client,role:transport,type:balance  client  {port:52792,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen} 


If you run same server with long pattern
- it outputs 1 ACT message


2016-02-10T19:00:38.289Z 1pgnzkzctk91/1455130838267/27836/- INFO        hello   Seneca/1.1.0/1pgnzkzctk91/1455130838267/27836/- 
2016-02-10T19:00:38.938Z 1pgnzkzctk91/1455130838267/27836/- INFO        listen  {pins:[ns:mmmmm,app:coi,ds:ba,w:a12345,cmd:fetch,ns:mmmmm,app:coi,ds:ba,w:a12345,cmd:publish],model:publish}  
2016-02-10T19:00:39.213Z 1pgnzkzctk91/1455130838267/27836/- WARN        -       -       ACT     45zp1fnz8vg8/joehsetwo5mj       name:mesh,plugin:define,role:seneca,seq:5,tag:undefined       plugin  mesh            {meta:{local:127.0.0.1:41277,hosts:[127.0.0.1:39999],numberOfHostsResponded:0,timeout:200}}

**Comment by rjrodger** [comment] 2016-07-23 11:20
This should be fixed now - the latest version of sneeze allows for up to 2048 bytes of meta data

**Closed by rjrodger** 2016-07-23 11:20 UTC
